/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::notionalCloud

Description
    Virtual abstract base class for templated notionalCloud

SourceFiles
    notionalCloud.C

\*---------------------------------------------------------------------------*/

#ifndef notionalCloud_H
#define notionalCloud_H

#include "typeInfo.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                  Class notionalCloud Declaration
\*---------------------------------------------------------------------------*/

class notionalCloud
{
    // Private Member Functions

        //- Disallow default bitwise copy construct
        notionalCloud(const notionalCloud&);

        //- Disallow default bitwise assignment
        void operator=(const notionalCloud&);


public:

    //- Runtime type information
    TypeName("notionalCloud");

    // Constructors

        //- Null constructor
        notionalCloud();


    //- Destructor
    virtual ~notionalCloud();
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
